package com.sumup.JobProcessor;

public final class Mocks {

  public static final String correctMockRequest = "{\n"
      + "\"tasks\":[\n"
      + "{\n"
      + "\"name\":\"task-1\",\n"
      + "\"command\":\"touch /tmp/file1\"\n"
      + "},\n"
      + "{\n"
      + "\"name\":\"task-2\",\n"
      + "\"command\":\"cat /tmp/file1\",\n"
      + "\"requires\":[\n"
      + "\"task-3\"\n"
      + "]\n"
      + "},\n"
      + "{\n"
      + "\"name\":\"task-3\",\n"
      + "\"command\":\"echo 'Hello World!' > /tmp/file1\",\n"
      + "\"requires\":[\n"
      + "\"task-1\"\n"
      + "]\n"
      + "},\n"
      + "{\n"
      + "\"name\":\"task-4\",\n"
      + "\"command\":\"rm /tmp/file1\",\n"
      + "\"requires\":[\n"
      + "\"task-2\",\n"
      + "\"task-3\"\n"
      + "]\n"
      + "}\n"
      + "]\n"
      + "}";

  public static final String expectedBashScriptResponse = "#!/usr/bin/env bash\r\n"
      + "touch /tmp/file1\r\n"
      + "echo 'Hello World!' > /tmp/file1\r\n"
      + "cat /tmp/file1\r\n"
      + "rm /tmp/file1\r\n";

  public static final String cyclicMockRequest = "{\n"
      + "\"tasks\":[\n"
      + "{\n"
      + "\"name\":\"task-1\",\n"
      + "\"command\":\"touch /tmp/file1\",\n"
      + "\"requires\":[\n"
      + "\"task-3\"\n"
      + "]\n"
      + "},\n"
      + "{\n"
      + "\"name\":\"task-2\",\n"
      + "\"command\":\"cat /tmp/file1\",\n"
      + "\"requires\":[\n"
      + "\"task-3\"\n"
      + "]\n"
      + "},\n"
      + "{\n"
      + "\"name\":\"task-3\",\n"
      + "\"command\":\"echo 'Hello World!' > /tmp/file1\",\n"
      + "\"requires\":[\n"
      + "\"task-1\"\n"
      + "]\n"
      + "},\n"
      + "{\n"
      + "\"name\":\"task-4\",\n"
      + "\"command\":\"rm /tmp/file1\",\n"
      + "\"requires\":[\n"
      + "\"task-2\",\n"
      + "\"task-3\"\n"
      + "]\n"
      + "}\n"
      + "]\n"
      + "}";

}
